# Generated by Django 2.0.8 on 2019-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='model_pic',
            field=models.ImageField(default='pic_folder/', upload_to='pic_folder/'),
        ),
    ]
