# Generated by Django 2.0.8 on 2019-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190127_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to='static/audio'),
        ),
    ]
