# Generated by Django 2.0.8 on 2019-01-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
    ]
